In [1]:
import pandas as pd
import re
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
data = pd.read_csv("Titanic-Dataset.csv")

# View data
data.head()
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
195,196,0,2,Passenger 196,male,5.4,2,3,TKT196,10.94,NaN,Q
196,197,1,3,Passenger 197,female,48.0,2,2,TKT197,91.45,NaN,S
197,198,0,3,Passenger 198,female,32.4,0,3,TKT198,84.61,C198,C
198,199,1,1,Passenger 199,male,53.8,1,3,TKT199,13.13,NaN,C
199,200,0,2,Passenger 200,male,38.6,3,3,TKT200,98.91,C200,Q

In [2]:
# Statistical summary
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,100.500000,0.525000,2.050000,40.279000,1.335000,1.460000,54.103000
std,57.879185,0.500628,0.794137,22.533418,1.191585,1.115627,25.706888
min,1.000000,0.000000,1.000000,2.100000,0.000000,0.000000,5.150000
25%,50.750000,0.000000,1.000000,21.275000,0.000000,0.000000,32.792500
50%,100.500000,1.000000,2.000000,41.700000,1.000000,2.000000,52.790000
75%,150.250000,1.000000,3.000000,57.325000,2.250000,2.000000,74.390000
max,200.000000,1.000000,3.000000,79.700000,3.000000,3.000000,99.910000

In [3]:
# Column names
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [4]:
# Check missing values
data.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
195,False,False,False,False,False,False,False,False,False,False,True,False
196,False,False,False,False,False,False,False,False,False,False,True,False
197,False,False,False,False,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False,False,False,True,False
199,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
# Count missing values
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          135
Embarked         0
dtype: int64

In [6]:
# Shape of dataset
print(data.shape)

(200, 12)